### ISSUE TITLE
[Fix] - Env.example

### ISSUE THREAD

**Issue by raugusto96** [PedrohvFernandes/servidor-de-email#1]
O que acha da ideia de separar os links de referencias do arquivo .env.example, para um arquivo ```references.md``` ou ```references.txt```?
Ajudaria na legibilidade do arquivo .env.example e ainda deixaria um arquivo para suas referencias.

**Comment by PedrohvFernandes** [comment]
Boa, vou aplicar essa ideia man, vai ficar bem mais limpo os exemplos das
envs

Em ter., 11 de abr. de 2023 às 14:56, Rodrigo Augusto <
***@***.***> escreveu:
